name: Publish Collection to Ansible Galaxy

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Ansible Publish
        # You may pin to the exact commit or the version.
        # uses: ansible/ansible-publish-action@a56a0328c92c1d4feedf5bd7f7cf7ec7a4ae3f09
        uses: artis3n/ansible_galaxy_collection@v2.10.1
        with:
          # Galaxy API key to use
          api_key: ${{ secrets.GALAXY_API_KEY }}
          # Galaxy API server to use, default being `https://galaxy.ansible.com`
          api_server: # optional, default is https://galaxy.ansible.com/
          # Specific path to collection, default being `.`
          src_path: ./