name: Publish Collection to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version name from the tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Print the version name
        run: echo $RELEASE_VERSION

      - name: Ansible Publish
        # You may pin to the exact commit or the version.
        # uses: ansible/ansible-publish-action@a56a0328c92c1d4feedf5bd7f7cf7ec7a4ae3f09
        uses: artis3n/ansible_galaxy_collection@v2.10.1
        with:
          # Galaxy API key to use
          api_key: ${{ secrets.GALAXY_API_KEY }}
          # Pass galaxy Version
          galaxy_version: '${{ env.RELEASE_VERSION }}'
          # galaxy file location
          galaxy_config_file: './galaxy.yml'  # Update this path to the correct location
          # Path to the collection
          collection_dir: './'
          # Build the collection
          build: false
          # Publish the collection
          publish: false
