name: Publish Collection to Ansible Galaxy on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version name from the git tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Print the version tag
        run: echo $RELEASE_VERSION

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ansible Publish
        uses: artis3n/ansible_galaxy_collection@v2.10.1
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          galaxy_version: '${{ env.RELEASE_VERSION }}'
          galaxy_config_file: './galaxy.yml'  # Update this path to the correct location
          collection_dir: './'
          build: true
          publish: true
